# Generated by Django 4.2.4 on 2024-01-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_amount_bid_bid_listing_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='amount',
        ),
    ]
