# Generated by Django 5.0.1 on 2024-04-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category_remove_listing_bid_remove_comment_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isLive',
            field=models.BooleanField(default=True),
        ),
    ]
